-- ==========================================
-- 0. EXTENSIONES
-- ==========================================
create extension if not exists vector;
create extension if not exists pg_trgm;
create extension if not exists "uuid-ossp";

-- ==========================================
-- 1. TABLAS BASE
-- ==========================================

-- Categorías del blog
create table public.categorias (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Clasificación normalizada de tipos de activo
create table public.tipos_activo (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Símbolos financieros vinculados al tipo
create table public.activos (
  id bigint generated by default as identity primary key,
  symbol text not null unique,
  name text not null,
  tipo_id bigint references public.tipos_activo(id) on delete restrict not null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Perfiles de autores (vinculado a auth.users)
create table public.perfiles_autores (
  id uuid references auth.users on delete cascade primary key,
  full_name text not null,
  avatar_url text,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Fuentes de noticias (attribution)
create table public.fuentes (
  id bigint generated by default as identity primary key,
  name text not null,
  url text,
  logo_url text,
  reliability_score int default 50 check (reliability_score between 0 and 100),
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Tags (más flexibles que categorías)
create table public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Posts principales
create table public.posts (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  slug text not null unique,
  content_html text not null,
  meta_title text,
  meta_description text,
  og_image_url text,
  twitter_card text default 'summary_large_image',
  sentiment text check (sentiment in ('bullish', 'bearish', 'neutral')),
  cover_image_url text,
  source_url text unique,
  source_id bigint references public.fuentes(id) on delete set null,
  status text default 'draft' check (status in ('draft', 'published', 'scheduled')),
  embedding vector(1536),
  search_vector tsvector,
  view_count bigint default 0,
  reading_time_minutes int,
  is_featured boolean default false,
  author_id uuid references public.perfiles_autores(id) on delete set null,
  category_id bigint references public.categorias(id) on delete set null,
  published_at timestamptz default timezone('utc'::text, now()),
  scheduled_at timestamptz,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Traducciones de posts (i18n ES/EN)
create table public.posts_translations (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  locale text not null check (locale in ('es', 'en')),
  title text not null,
  slug text not null,
  content_html text not null,
  meta_title text,
  meta_description text,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null,
  unique (post_id, locale),
  unique (locale, slug)
);

-- Relación many-to-many posts <-> activos
create table public.post_activos (
  post_id uuid references public.posts(id) on delete cascade,
  asset_id bigint references public.activos(id) on delete cascade,
  primary key (post_id, asset_id)
);

-- Relación many-to-many posts <-> tags
create table public.post_tags (
  post_id uuid references public.posts(id) on delete cascade,
  tag_id bigint references public.tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

-- ==========================================
-- 2. ÍNDICES DE RENDIMIENTO
-- ==========================================

-- Posts
create index posts_slug_idx on public.posts (slug);
create index posts_status_idx on public.posts (status);
create index posts_status_published_at_idx on public.posts (status, published_at desc);
create index posts_category_status_idx on public.posts (category_id, status);
create index posts_author_status_idx on public.posts (author_id, status);
create index posts_scheduled_at_idx on public.posts (scheduled_at) where status = 'scheduled';
create index posts_is_featured_idx on public.posts (is_featured) where is_featured = true;
create index posts_source_id_idx on public.posts (source_id);
create index posts_search_vector_idx on public.posts using gin (search_vector);

-- Activos
create index activos_symbol_idx on public.activos (symbol);
create index activos_tipo_id_idx on public.activos (tipo_id);

-- Categorías, tipos, fuentes, tags
create index categorias_slug_idx on public.categorias (slug);
create index tipos_activo_slug_idx on public.tipos_activo (slug);
create index fuentes_name_idx on public.fuentes (name);
create index tags_slug_idx on public.tags (slug);

-- Traducciones
create index posts_translations_post_id_idx on public.posts_translations (post_id);
create index posts_translations_locale_slug_idx on public.posts_translations (locale, slug);

-- ==========================================
-- 3. TRIGGERS: updated_at Y search_vector
-- ==========================================

-- Función genérica updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end $$;

-- Trigger updated_at en todas las tablas
create trigger trigger_categorias_updated_at before update on public.categorias for each row execute function public.set_updated_at();
create trigger trigger_tipos_activo_updated_at before update on public.tipos_activo for each row execute function public.set_updated_at();
create trigger trigger_activos_updated_at before update on public.activos for each row execute function public.set_updated_at();
create trigger trigger_perfiles_autores_updated_at before update on public.perfiles_autores for each row execute function public.set_updated_at();
create trigger trigger_fuentes_updated_at before update on public.fuentes for each row execute function public.set_updated_at();
create trigger trigger_tags_updated_at before update on public.tags for each row execute function public.set_updated_at();
create trigger trigger_posts_updated_at before update on public.posts for each row execute function public.set_updated_at();
create trigger trigger_posts_translations_updated_at before update on public.posts_translations for each row execute function public.set_updated_at();

-- Función search_vector (full-text search español + inglés)
create or replace function public.update_posts_search_vector()
returns trigger language plpgsql as $$
begin
  new.search_vector :=
    setweight(to_tsvector('spanish', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(new.content_html, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.content_html, '')), 'B');
  return new;
end $$;

create trigger trigger_posts_search_vector before insert or update on public.posts
for each row execute function public.update_posts_search_vector();

-- ==========================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ==========================================

alter table public.categorias enable row level security;
alter table public.tipos_activo enable row level security;
alter table public.activos enable row level security;
alter table public.fuentes enable row level security;
alter table public.tags enable row level security;
alter table public.perfiles_autores enable row level security;
alter table public.posts enable row level security;
alter table public.post_activos enable row level security;
alter table public.post_tags enable row level security;
alter table public.posts_translations enable row level security;

-- Lectura pública
create policy "Lectura publica categorias" on public.categorias for select to anon, authenticated using (true);
create policy "Lectura publica tipos_activo" on public.tipos_activo for select to anon, authenticated using (true);
create policy "Lectura publica activos" on public.activos for select to anon, authenticated using (true);
create policy "Lectura publica fuentes" on public.fuentes for select to anon, authenticated using (true);
create policy "Lectura publica tags" on public.tags for select to anon, authenticated using (true);
create policy "Lectura publica post_activos" on public.post_activos for select to anon, authenticated using (true);
create policy "Lectura publica post_tags" on public.post_tags for select to anon, authenticated using (true);
create policy "Lectura publica posts_translations" on public.posts_translations for select to anon, authenticated using (true);

-- Posts: solo publicados (o programados que ya pasó su fecha)
create policy "Lectura posts publicados" on public.posts for select to anon, authenticated
using (
  status = 'published'
  or (status = 'scheduled' and scheduled_at <= timezone('utc'::text, now()))
);

-- Autores gestionan sus posts
create policy "Autores gestionan sus posts" on public.posts for all to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

-- Autores editan su perfil
create policy "Autores editan su perfil" on public.perfiles_autores for all to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Service role (n8n, cron jobs): acceso total a posts, lecturas a catálogos
create policy "Service role full access posts" on public.posts for all to service_role using (true) with check (true);
create policy "Service role read catalogos" on public.categorias for select to service_role using (true);
create policy "Service role read tipos_activo" on public.tipos_activo for select to service_role using (true);
create policy "Service role read activos" on public.activos for select to service_role using (true);
create policy "Service role read fuentes" on public.fuentes for select to service_role using (true);
create policy "Service role read tags" on public.tags for select to service_role using (true);
create policy "Service role read post_activos" on public.post_activos for all to service_role using (true) with check (true);
create policy "Service role read post_tags" on public.post_tags for all to service_role using (true) with check (true);
create policy "Service role read posts_translations" on public.posts_translations for all to service_role using (true) with check (true);

-- ==========================================
-- 5. FUNCIONES RPC Y HELPERS
-- ==========================================

-- Calcular reading_time_minutes aprox (200 palabras/min)
create or replace function public.calculate_reading_time(content text)
returns int language sql immutable as $$
  select greatest(1, round((length(regexp_replace(content, '<[^>]+>', '', 'g')) / 5) / 200.0)::int);
$$;

-- Publicar posts programados (llamar via pg_cron cada minuto)
create or replace function public.publish_scheduled_posts()
returns int language plpgsql as $$
declare
  updated_count int;
begin
  update public.posts
  set status = 'published', published_at = timezone('utc'::text, now()), updated_at = timezone('utc'::text, now())
  where status = 'scheduled' and scheduled_at <= timezone('utc'::text, now())
  returning 1 into updated_count;
  return coalesce(updated_count, 0);
end $$;

-- Búsqueda full-text (uso: select * from search_posts('bitcoin ether', 'es'))
create or replace function public.search_posts(query_text text, locale_param text default 'es', limit_count int default 20)
returns setof public.posts language plpgsql as $$
begin
  return query
  select p.* from public.posts p
  where p.status = 'published'
    and p.search_vector @@ plainto_tsvector(
      case when locale_param = 'en' then 'english' else 'spanish' end,
      query_text
    )
  order by ts_rank_cd(p.search_vector, plainto_tsvector(
      case when locale_param = 'en' then 'english' else 'spanish' end,
      query_text
    )) desc, p.published_at desc
  limit limit_count;
end $$;

-- ==========================================
-- 6. DATOS INICIALES (MOCK DATA)
-- ==========================================

-- Categorías
insert into public.categorias (name, slug) values 
  ('Criptomonedas', 'criptomonedas'),
  ('Forex', 'forex'),
  ('Materias Primas', 'materias-primas'),
  ('Acciones', 'acciones')
on conflict (slug) do nothing;

-- Tipos de activo
insert into public.tipos_activo (name, slug) values 
  ('Crypto', 'crypto'),
  ('Forex', 'forex'),
  ('Commodity', 'commodity'),
  ('Stock', 'stock'),
  ('Index', 'index')
on conflict (slug) do nothing;

-- Activos (tipo_id: 1=Crypto, 2=Forex, 3=Commodity, 4=Stock, 5=Index)
insert into public.activos (symbol, name, tipo_id) values 
  ('BTC', 'Bitcoin', 1),
  ('ETH', 'Ethereum', 1),
  ('SOL', 'Solana', 1),
  ('EURUSD', 'Euro / Dólar', 2),
  ('GBPUSD', 'Libra / Dólar', 2),
  ('XAUUSD', 'Oro', 3),
  ('XAGUSD', 'Plata', 3),
  ('AAPL', 'Apple Inc.', 4),
  ('NVDA', 'Nvidia', 4),
  ('SPX', 'S&P 500', 5),
  ('DXY', 'Dollar Index', 5)
on conflict (symbol) do nothing;

-- Fuentes iniciales
insert into public.fuentes (name, url, logo_url, reliability_score) values
  ('Bloomberg', 'https://bloomberg.com', null, 95),
  ('Reuters', 'https://reuters.com', null, 95),
  ('CoinDesk', 'https://coindesk.com', null, 85),
  ('Investing.com', 'https://investing.com', null, 80),
  ('TradingView News', 'https://tradingview.com', null, 75),
  ('Forex Factory', 'https://forexfactory.com', null, 70)
on conflict do nothing;

-- Tags iniciales
insert into public.tags (name, slug) values
  ('Análisis Técnico', 'analisis-tecnico'),
  ('Fundamental', 'fundamental'),
  ('Macroeconomía', 'macroeconomia'),
  ('DeFi', 'defi'),
  ('ETF', 'etf'),
  ('Banco Central', 'banco-central'),
  ('Earnings', 'earnings'),
  ('Halving', 'halving')
on conflict (slug) do nothing;

-- ==========================================
-- 7. PG_CRON PARA PUBLICACIÓN PROGRAMADA (OPCIONAL)
-- ==========================================
-- Habilitar en Supabase: Settings > Database > Extensions > pg_cron
-- Luego ejecutar:
-- select cron.schedule('publish-scheduled-posts', '* * * * *', 'select public.publish_scheduled_posts();');

-- ==========================================
-- 8. COMENTARIOS PARA FUTURO
-- ==========================================
-- Índice vectorial (crear cuando activen búsqueda semántica):
-- create index posts_embedding_idx on public.posts using hnsw (embedding vector_cosine_ops)
-- with (m = 16, ef_construction = 64);
-- Requiere: pgvector >= 0.5.0 y tabla con >1000 rows para beneficio real