-- Generado por scripts/generate-assets-seed.ts desde lib/assets-catalog.ts — no editar a mano,
-- volver a correr el script y pegar la salida si el catálogo cambió.
insert into public.activos (symbol, name, tipo_id) values
  ('BTC', 'Bitcoin', 1),
  ('ETH', 'Ethereum', 1),
  ('SOL', 'Solana', 1),
  ('BNB', 'BNB', 1),
  ('XRP', 'XRP', 1),
  ('ADA', 'Cardano', 1),
  ('DOGE', 'Dogecoin', 1),
  ('DOT', 'Polkadot', 1),
  ('AVAX', 'Avalanche', 1),
  ('LINK', 'Chainlink', 1),
  ('POL', 'Polygon', 1),
  ('UNI', 'Uniswap', 1),
  ('ATOM', 'Cosmos', 1),
  ('LTC', 'Litecoin', 1),
  ('NEAR', 'NEAR Protocol', 1),
  ('EURUSD', 'Euro / Dólar', 2),
  ('GBPUSD', 'Libra / Dólar', 2),
  ('USDJPY', 'Dólar / Yen', 2),
  ('USDCHF', 'Dólar / Franco suizo', 2),
  ('AUDUSD', 'Dólar australiano / Dólar', 2),
  ('USDCAD', 'Dólar / Dólar canadiense', 2),
  ('NZDUSD', 'Dólar neozelandés / Dólar', 2),
  ('EURGBP', 'Euro / Libra', 2),
  ('EURJPY', 'Euro / Yen', 2),
  ('GBPJPY', 'Libra / Yen', 2),
  ('XAUUSD', 'Oro', 3),
  ('XAGUSD', 'Plata', 3),
  ('PLATINUM', 'Platino', 3),
  ('PALLADIUM', 'Paladio', 3),
  ('BRENT', 'Petróleo Brent', 3),
  ('WTI', 'Petróleo WTI', 3),
  ('NG', 'Gas natural', 3),
  ('COPPER', 'Cobre', 3),
  ('CORN', 'Maíz', 3),
  ('WHEAT', 'Trigo', 3),
  ('SUGAR', 'Azúcar', 3),
  ('COFFEE', 'Café', 3),
  ('AAPL', 'Apple', 4),
  ('NVDA', 'Nvidia', 4),
  ('MSFT', 'Microsoft', 4),
  ('GOOGL', 'Alphabet', 4),
  ('AMZN', 'Amazon', 4),
  ('META', 'Meta', 4),
  ('TSLA', 'Tesla', 4),
  ('AMD', 'AMD', 4),
  ('NFLX', 'Netflix', 4),
  ('INTC', 'Intel', 4),
  ('JPM', 'JPMorgan Chase', 4),
  ('V', 'Visa', 4),
  ('JNJ', 'Johnson & Johnson', 4),
  ('UNH', 'UnitedHealth', 4),
  ('SPX', 'S&P 500', 5),
  ('NDX', 'Nasdaq 100', 5),
  ('DJI', 'Dow Jones Industrial', 5),
  ('DXY', 'Índice del dólar', 5),
  ('DAX', 'DAX 40 (Alemania)', 5),
  ('FTSE', 'FTSE 100 (Reino Unido)', 5),
  ('CAC40', 'CAC 40 (Francia)', 5),
  ('ESTX50', 'Euro Stoxx 50', 5),
  ('NIKKEI', 'Nikkei 225 (Japón)', 5),
  ('HSI', 'Hang Seng (Hong Kong)', 5),
  ('VIX', 'Índice de volatilidad', 5),
  ('US10Y', 'Bono de EE. UU. a 10 años', 5),
  ('US02Y', 'Bono de EE. UU. a 2 años', 5)
on conflict (symbol) do nothing;

-- Reconcilia drift: activos que ya existían con un name/tipo_id distinto al del catálogo actual.
update public.activos a set name = v.name, tipo_id = v.tipo_id
from (values
  ('BTC', 'Bitcoin', 1),
  ('ETH', 'Ethereum', 1),
  ('SOL', 'Solana', 1),
  ('BNB', 'BNB', 1),
  ('XRP', 'XRP', 1),
  ('ADA', 'Cardano', 1),
  ('DOGE', 'Dogecoin', 1),
  ('DOT', 'Polkadot', 1),
  ('AVAX', 'Avalanche', 1),
  ('LINK', 'Chainlink', 1),
  ('POL', 'Polygon', 1),
  ('UNI', 'Uniswap', 1),
  ('ATOM', 'Cosmos', 1),
  ('LTC', 'Litecoin', 1),
  ('NEAR', 'NEAR Protocol', 1),
  ('EURUSD', 'Euro / Dólar', 2),
  ('GBPUSD', 'Libra / Dólar', 2),
  ('USDJPY', 'Dólar / Yen', 2),
  ('USDCHF', 'Dólar / Franco suizo', 2),
  ('AUDUSD', 'Dólar australiano / Dólar', 2),
  ('USDCAD', 'Dólar / Dólar canadiense', 2),
  ('NZDUSD', 'Dólar neozelandés / Dólar', 2),
  ('EURGBP', 'Euro / Libra', 2),
  ('EURJPY', 'Euro / Yen', 2),
  ('GBPJPY', 'Libra / Yen', 2),
  ('XAUUSD', 'Oro', 3),
  ('XAGUSD', 'Plata', 3),
  ('PLATINUM', 'Platino', 3),
  ('PALLADIUM', 'Paladio', 3),
  ('BRENT', 'Petróleo Brent', 3),
  ('WTI', 'Petróleo WTI', 3),
  ('NG', 'Gas natural', 3),
  ('COPPER', 'Cobre', 3),
  ('CORN', 'Maíz', 3),
  ('WHEAT', 'Trigo', 3),
  ('SUGAR', 'Azúcar', 3),
  ('COFFEE', 'Café', 3),
  ('AAPL', 'Apple', 4),
  ('NVDA', 'Nvidia', 4),
  ('MSFT', 'Microsoft', 4),
  ('GOOGL', 'Alphabet', 4),
  ('AMZN', 'Amazon', 4),
  ('META', 'Meta', 4),
  ('TSLA', 'Tesla', 4),
  ('AMD', 'AMD', 4),
  ('NFLX', 'Netflix', 4),
  ('INTC', 'Intel', 4),
  ('JPM', 'JPMorgan Chase', 4),
  ('V', 'Visa', 4),
  ('JNJ', 'Johnson & Johnson', 4),
  ('UNH', 'UnitedHealth', 4),
  ('SPX', 'S&P 500', 5),
  ('NDX', 'Nasdaq 100', 5),
  ('DJI', 'Dow Jones Industrial', 5),
  ('DXY', 'Índice del dólar', 5),
  ('DAX', 'DAX 40 (Alemania)', 5),
  ('FTSE', 'FTSE 100 (Reino Unido)', 5),
  ('CAC40', 'CAC 40 (Francia)', 5),
  ('ESTX50', 'Euro Stoxx 50', 5),
  ('NIKKEI', 'Nikkei 225 (Japón)', 5),
  ('HSI', 'Hang Seng (Hong Kong)', 5),
  ('VIX', 'Índice de volatilidad', 5),
  ('US10Y', 'Bono de EE. UU. a 10 años', 5),
  ('US02Y', 'Bono de EE. UU. a 2 años', 5)
) as v(symbol, name, tipo_id)
where a.symbol = v.symbol
  and (a.name is distinct from v.name or a.tipo_id is distinct from v.tipo_id);
