-- Generado por scripts/generate-assets-seed.ts desde lib/assets-catalog.ts — no editar a mano,
-- volver a correr el script y pegar la salida si el catálogo cambió.
-- `name_en` (Fase 5 del plan de cobertura en inglés) requiere que la columna ya exista —
-- correr primero el `alter table` si es una base que todavía no la tiene.
alter table public.activos add column if not exists name_en text;

insert into public.activos (symbol, name, tipo_id, name_en) values
  ('BTC', 'Bitcoin', 1, 'Bitcoin'),
  ('ETH', 'Ethereum', 1, 'Ethereum'),
  ('SOL', 'Solana', 1, 'Solana'),
  ('BNB', 'BNB', 1, 'BNB'),
  ('XRP', 'XRP', 1, 'XRP'),
  ('ADA', 'Cardano', 1, 'Cardano'),
  ('DOGE', 'Dogecoin', 1, 'Dogecoin'),
  ('DOT', 'Polkadot', 1, 'Polkadot'),
  ('AVAX', 'Avalanche', 1, 'Avalanche'),
  ('LINK', 'Chainlink', 1, 'Chainlink'),
  ('POL', 'Polygon', 1, 'Polygon'),
  ('UNI', 'Uniswap', 1, 'Uniswap'),
  ('ATOM', 'Cosmos', 1, 'Cosmos'),
  ('LTC', 'Litecoin', 1, 'Litecoin'),
  ('NEAR', 'NEAR Protocol', 1, 'NEAR Protocol'),
  ('EURUSD', 'Euro / Dólar', 2, 'Euro / US Dollar'),
  ('GBPUSD', 'Libra / Dólar', 2, 'British Pound / US Dollar'),
  ('USDJPY', 'Dólar / Yen', 2, 'US Dollar / Japanese Yen'),
  ('USDCHF', 'Dólar / Franco suizo', 2, 'US Dollar / Swiss Franc'),
  ('AUDUSD', 'Dólar australiano / Dólar', 2, 'Australian Dollar / US Dollar'),
  ('USDCAD', 'Dólar / Dólar canadiense', 2, 'US Dollar / Canadian Dollar'),
  ('NZDUSD', 'Dólar neozelandés / Dólar', 2, 'New Zealand Dollar / US Dollar'),
  ('EURGBP', 'Euro / Libra', 2, 'Euro / British Pound'),
  ('EURJPY', 'Euro / Yen', 2, 'Euro / Japanese Yen'),
  ('GBPJPY', 'Libra / Yen', 2, 'British Pound / Japanese Yen'),
  ('XAUUSD', 'Oro', 3, 'Gold'),
  ('XAGUSD', 'Plata', 3, 'Silver'),
  ('PLATINUM', 'Platino', 3, 'Platinum'),
  ('PALLADIUM', 'Paladio', 3, 'Palladium'),
  ('BRENT', 'Petróleo Brent', 3, 'Brent Crude Oil'),
  ('WTI', 'Petróleo WTI', 3, 'WTI Crude Oil'),
  ('NG', 'Gas natural', 3, 'Natural Gas'),
  ('COPPER', 'Cobre', 3, 'Copper'),
  ('CORN', 'Maíz', 3, 'Corn'),
  ('WHEAT', 'Trigo', 3, 'Wheat'),
  ('SUGAR', 'Azúcar', 3, 'Sugar'),
  ('COFFEE', 'Café', 3, 'Coffee'),
  ('AAPL', 'Apple', 4, 'Apple'),
  ('NVDA', 'Nvidia', 4, 'Nvidia'),
  ('MSFT', 'Microsoft', 4, 'Microsoft'),
  ('GOOGL', 'Alphabet', 4, 'Alphabet'),
  ('AMZN', 'Amazon', 4, 'Amazon'),
  ('META', 'Meta', 4, 'Meta'),
  ('TSLA', 'Tesla', 4, 'Tesla'),
  ('AMD', 'AMD', 4, 'AMD'),
  ('NFLX', 'Netflix', 4, 'Netflix'),
  ('INTC', 'Intel', 4, 'Intel'),
  ('JPM', 'JPMorgan Chase', 4, 'JPMorgan Chase'),
  ('V', 'Visa', 4, 'Visa'),
  ('JNJ', 'Johnson & Johnson', 4, 'Johnson & Johnson'),
  ('UNH', 'UnitedHealth', 4, 'UnitedHealth'),
  ('SPX', 'S&P 500', 5, 'S&P 500'),
  ('NDX', 'Nasdaq 100', 5, 'Nasdaq 100'),
  ('DJI', 'Dow Jones Industrial', 5, 'Dow Jones Industrial Average'),
  ('DXY', 'Índice del dólar', 5, 'US Dollar Index'),
  ('DAX', 'DAX 40 (Alemania)', 5, 'DAX 40 (Germany)'),
  ('FTSE', 'FTSE 100 (Reino Unido)', 5, 'FTSE 100 (United Kingdom)'),
  ('CAC40', 'CAC 40 (Francia)', 5, 'CAC 40 (France)'),
  ('ESTX50', 'Euro Stoxx 50', 5, 'Euro Stoxx 50'),
  ('NIKKEI', 'Nikkei 225 (Japón)', 5, 'Nikkei 225 (Japan)'),
  ('HSI', 'Hang Seng (Hong Kong)', 5, 'Hang Seng (Hong Kong)'),
  ('VIX', 'Índice de volatilidad', 5, 'Volatility Index'),
  ('US10Y', 'Bono de EE. UU. a 10 años', 5, 'US 10-Year Treasury Note'),
  ('US02Y', 'Bono de EE. UU. a 2 años', 5, 'US 2-Year Treasury Note')
on conflict (symbol) do nothing;

-- Reconcilia drift: activos que ya existían con un name/tipo_id/name_en distinto al del catálogo actual.
update public.activos a set name = v.name, tipo_id = v.tipo_id, name_en = v.name_en
from (values
  ('BTC', 'Bitcoin', 1, 'Bitcoin'),
  ('ETH', 'Ethereum', 1, 'Ethereum'),
  ('SOL', 'Solana', 1, 'Solana'),
  ('BNB', 'BNB', 1, 'BNB'),
  ('XRP', 'XRP', 1, 'XRP'),
  ('ADA', 'Cardano', 1, 'Cardano'),
  ('DOGE', 'Dogecoin', 1, 'Dogecoin'),
  ('DOT', 'Polkadot', 1, 'Polkadot'),
  ('AVAX', 'Avalanche', 1, 'Avalanche'),
  ('LINK', 'Chainlink', 1, 'Chainlink'),
  ('POL', 'Polygon', 1, 'Polygon'),
  ('UNI', 'Uniswap', 1, 'Uniswap'),
  ('ATOM', 'Cosmos', 1, 'Cosmos'),
  ('LTC', 'Litecoin', 1, 'Litecoin'),
  ('NEAR', 'NEAR Protocol', 1, 'NEAR Protocol'),
  ('EURUSD', 'Euro / Dólar', 2, 'Euro / US Dollar'),
  ('GBPUSD', 'Libra / Dólar', 2, 'British Pound / US Dollar'),
  ('USDJPY', 'Dólar / Yen', 2, 'US Dollar / Japanese Yen'),
  ('USDCHF', 'Dólar / Franco suizo', 2, 'US Dollar / Swiss Franc'),
  ('AUDUSD', 'Dólar australiano / Dólar', 2, 'Australian Dollar / US Dollar'),
  ('USDCAD', 'Dólar / Dólar canadiense', 2, 'US Dollar / Canadian Dollar'),
  ('NZDUSD', 'Dólar neozelandés / Dólar', 2, 'New Zealand Dollar / US Dollar'),
  ('EURGBP', 'Euro / Libra', 2, 'Euro / British Pound'),
  ('EURJPY', 'Euro / Yen', 2, 'Euro / Japanese Yen'),
  ('GBPJPY', 'Libra / Yen', 2, 'British Pound / Japanese Yen'),
  ('XAUUSD', 'Oro', 3, 'Gold'),
  ('XAGUSD', 'Plata', 3, 'Silver'),
  ('PLATINUM', 'Platino', 3, 'Platinum'),
  ('PALLADIUM', 'Paladio', 3, 'Palladium'),
  ('BRENT', 'Petróleo Brent', 3, 'Brent Crude Oil'),
  ('WTI', 'Petróleo WTI', 3, 'WTI Crude Oil'),
  ('NG', 'Gas natural', 3, 'Natural Gas'),
  ('COPPER', 'Cobre', 3, 'Copper'),
  ('CORN', 'Maíz', 3, 'Corn'),
  ('WHEAT', 'Trigo', 3, 'Wheat'),
  ('SUGAR', 'Azúcar', 3, 'Sugar'),
  ('COFFEE', 'Café', 3, 'Coffee'),
  ('AAPL', 'Apple', 4, 'Apple'),
  ('NVDA', 'Nvidia', 4, 'Nvidia'),
  ('MSFT', 'Microsoft', 4, 'Microsoft'),
  ('GOOGL', 'Alphabet', 4, 'Alphabet'),
  ('AMZN', 'Amazon', 4, 'Amazon'),
  ('META', 'Meta', 4, 'Meta'),
  ('TSLA', 'Tesla', 4, 'Tesla'),
  ('AMD', 'AMD', 4, 'AMD'),
  ('NFLX', 'Netflix', 4, 'Netflix'),
  ('INTC', 'Intel', 4, 'Intel'),
  ('JPM', 'JPMorgan Chase', 4, 'JPMorgan Chase'),
  ('V', 'Visa', 4, 'Visa'),
  ('JNJ', 'Johnson & Johnson', 4, 'Johnson & Johnson'),
  ('UNH', 'UnitedHealth', 4, 'UnitedHealth'),
  ('SPX', 'S&P 500', 5, 'S&P 500'),
  ('NDX', 'Nasdaq 100', 5, 'Nasdaq 100'),
  ('DJI', 'Dow Jones Industrial', 5, 'Dow Jones Industrial Average'),
  ('DXY', 'Índice del dólar', 5, 'US Dollar Index'),
  ('DAX', 'DAX 40 (Alemania)', 5, 'DAX 40 (Germany)'),
  ('FTSE', 'FTSE 100 (Reino Unido)', 5, 'FTSE 100 (United Kingdom)'),
  ('CAC40', 'CAC 40 (Francia)', 5, 'CAC 40 (France)'),
  ('ESTX50', 'Euro Stoxx 50', 5, 'Euro Stoxx 50'),
  ('NIKKEI', 'Nikkei 225 (Japón)', 5, 'Nikkei 225 (Japan)'),
  ('HSI', 'Hang Seng (Hong Kong)', 5, 'Hang Seng (Hong Kong)'),
  ('VIX', 'Índice de volatilidad', 5, 'Volatility Index'),
  ('US10Y', 'Bono de EE. UU. a 10 años', 5, 'US 10-Year Treasury Note'),
  ('US02Y', 'Bono de EE. UU. a 2 años', 5, 'US 2-Year Treasury Note')
) as v(symbol, name, tipo_id, name_en)
where a.symbol = v.symbol
  and (a.name is distinct from v.name or a.tipo_id is distinct from v.tipo_id or a.name_en is distinct from v.name_en);
